# Generated by Django 5.2 on 2025-05-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favoriterecipe_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.TextField(help_text='Добавьте визуальное представление рецепта', verbose_name='Фото рецепта'),
        ),
    ]
