# Generated by Django 5.2 on 2025-05-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Добавьте визуальное представление рецепта', upload_to='recipes/images/', verbose_name='Фото рецепта'),
        ),
    ]
