# Generated by Django 5.2 on 2025-05-30 15:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите ваш аватар', null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким юзернеймом уже существует.'}, help_text='Укажите ваш юзернейм (никнейм). Допустимые символы: буквы, цифры и @/./+/-/_', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя содержит недопустимые символы.', regex='^[\\w.@+-]+$')], verbose_name='Уникальный юзернейм'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('user', 'author'), name='unique_user_author_subscription'), models.CheckConstraint(condition=models.Q(('user', models.F('author')), _negated=True), name='prevent_self_subscription')],
            },
        ),
    ]
