# Generated by Django 5.2 on 2025-05-20 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250412_2321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='UserSubscription',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким юзернеймом уже существует.'}, help_text='Укажите ваш юзернейм (никнейм). Допустимые символы: буквы, цифры и @/./+/-/_', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя содержит недопустимые символы.', regex='^[\\w.@+-]+$')], verbose_name='Уникальный юзернейм'),
        ),
    ]
