# Generated by Django 5.2 on 2025-05-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите ваш аватар', null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
    ]
